services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 1338:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start
    ports:
      - 8001:8001
    restart: unless-stopped
    env_file:
      - .env/.env.docker
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start-celeryworker
    env_file:
      - .env/.env.docker
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start-celerybeat
    env_file:
      - .env/.env.docker
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start-flower
    env_file:
      - .env/.env.docker
    ports:
      - 5555:5555
    depends_on:
      - redis